name: Rust

on: [push, pull_request]

defaults:
  run:
    shell: bash

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-hack

    - run: rustup update stable && rustup default stable
    - run: cargo hack clippy --all-targets --feature-powerset
    - run: cargo hack test --feature-powerset
    - run: cargo hack test --feature-powerset --rust-version

    - run: rustup update nightly && rustup default nightly
    - run: rustup component add miri
    - run: cargo +nightly miri setup
    - run: cargo +nightly miri test --all-features
    - run: cargo +nightly miri setup --target=x86_64-pc-windows-msvc
    - run: cargo +nightly miri test --all-features --target=x86_64-pc-windows-msvc
